<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mailchimp.mailchimppro.customer_sync' shared service.

return $this->services['mailchimp.mailchimppro.customer_sync'] = new \PrestaChamps\MailchimpPro\Console\Commands\CustomersSyncCommand();
