<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'timactive.giftcard.set_up_shop_demo' shared service.

return $this->services['timactive.giftcard.set_up_shop_demo'] = new \TimActive\Module\GiftCard\Command\SetUpShopDemoCommand();
