<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoqqus2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoqqus2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUoqqus2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUoqqus2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUoqqus2\appProdProjectContainer([
    'container.build_hash' => 'Uoqqus2',
    'container.build_id' => 'e2509edc',
    'container.build_time' => 1736189490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoqqus2');
