<?php
/**
 * Copyright ETS Software Technology Co., Ltd
 *
 * NOTICE OF LICENSE
 *
 * This file is not open source! Each license that you purchased is only available for 1 website only.
 * If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future.
 *
 * @author ETS Software Technology Co., Ltd
 * @copyright  ETS Software Technology Co., Ltd
 * @license    Valid for 1 website (or project) for each purchase of license
 */

if (!defined('_PS_VERSION_')) { exit; }
class MLS_Slide extends MLS_Obj
{
    public $id_slide;
    public $image;    
    public $sort_order;
    public $backgroud_color;
    public $enabled;
    public $animation_in;
    public $animation_out;
    public $title;
    public $repeat_x;
    public $repeat_y;
    public $custom_class;
    public static $definition = array(
		'table' => 'ets_mls_slide',
		'primary' => 'id_slide',
		'multilang' => true,
		'fields' => array(
			'image' => array('type' => self::TYPE_STRING), 
            'sort_order' => array('type' => self::TYPE_INT),   
            'backgroud_color' => array('type' => self::TYPE_STRING),
            'enabled' => array('type' => self::TYPE_INT),
            'repeat_x' => array('type' => self::TYPE_INT),
            'repeat_y' => array('type' => self::TYPE_INT),
            'animation_in' => array('type' => self::TYPE_STRING),
            'animation_out' => array('type' => self::TYPE_STRING),
            'custom_class' => array('type' => self::TYPE_STRING),
            // Lang fields
            'title' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isCleanHtml'),			            
        )
	);
    public	function __construct($id_item = null, $id_lang = null, $id_shop = null, Context $context = null)
	{
		parent::__construct($id_item, $id_lang, $id_shop);
        $languages = Language::getLanguages(false);         
        foreach($languages as $lang)
        {
            foreach(self::$definition['fields'] as $field => $params)
            {   
                $temp = $this->$field; 
                if(isset($params['lang']) && $params['lang'] && !isset($temp[$lang['id_lang']]))
                {                      
                    $temp[$lang['id_lang']] = '';                        
                }
                $this->$field = $temp;
            }
        }
        unset($context);        
        $this->setFields(Ets_mls_defines::getSliders($id_item));
	}
	public function add($auto_date = true, $null_values = false)
	{
		$this->module->_clearCacheWhenUpdateSlide($this->id);
		return parent::add($auto_date, $null_values); // TODO: Change the autogenerated stub
	}

	public function update($null_values = false)
	{
		$this->module->_clearCacheWhenUpdateSlide($this->id);
		return parent::update($null_values); // TODO: Change the autogenerated stub
	}

	public function delete()
	{
		$this->module->_clearCacheWhenUpdateSlide($this->id);
		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
